# Generated by Django 3.2 on 2023-03-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_category_menuitem_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nome',
        ),
    ]
