# Generated by Django 3.2 on 2023-03-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20230314_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='descricao',
            new_name='description',
        ),
    ]
