# Generated by Django 3.2 on 2023-03-14 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='menu_images/', validators=[django.core.validators.FileExtensionValidator(['jpeg'])]),
        ),
    ]
